[Source]

# ------------------------------------------------------------------------------
# Image source
#   disk  : Read image files from disk. Needs `image_path` set.
#   webcam: Live capture from webcam. Needs `camera_id` set.
#   Ximea : Live capture from Ximea camera. Needs `camera_id` set.
image_source = disk

# ------------------------------------------------------------------------------
# Absolute or relative path to the image files in case of `image_source = disk`.
# The path should end in a wildcard pointing to the images to read, e.g.
#   ../test_imgs/PIV_rising_vortex_plume/*.png
image_path = ../test_imgs/swirling_vortices/*.tif

# ------------------------------------------------------------------------------
# Id of the camera to connect to in case of `image_source = webcam | Ximea`. If
# only one camera is attached the id will be 0.
camera_id = 0



[Processing]

# ------------------------------------------------------------------------------
# Mode:
#   PIV
#       Particle image velocimetry using equidistantly timed frames.
#       (frame_0, frame_1), (frame_1, frame_2), (frame_2, frame_3), ...
#
#   PIV2
#       Particle image velocimetry using image pairs.
#       (frame_0, frame_1), (frame_2, frame_3), (frame_4, frame_5), ...
#
#   BOS
#       Background-oriented Schlieren.
#       (frame_0, frame_1), (frame_0, frame_2), (frame_0, frame_3), ...
mode = PIV2

# ------------------------------------------------------------------------------
# List of square interrogation window sizes in [px] for the multigrid analysis.
# Use powers of two with each subsequent IW size the exact half of the previous
# IW size. Generally, you should not go smaller than 32 or 16 px.
# HINT: PIV usually benefits from using a multigrid analysis. BOS tends to not
# need it and work just fine using a single small IW size.
IW_sizes = [128, 64, 32]

# ------------------------------------------------------------------------------
# Interrogation window overlap fraction [0 - 0.5]. Only the last multigrid stage
# will have window overlapping applied to it.
IW_overlap = 0.5



[Plotting]

quiver_size = 1
color_div = 24



[Advanced]

# ------------------------------------------------------------------------------
# FFT library to use for computing 2D correlations:
#   rocketfft
#       The fastest of all, because `rocketfft` is fully jitted by numba and
#       releases the GIL.
#
#   scipy
#       Slightly slower than `rocketfft`. Also `scipy` is fully jitted by numba
#       and releases the GIL.
#
#   pyfftw
#       The slowest of all, because `pyfftw` can not be jitted by numba and
#       does not release the GIL when `N_FFT_threads = 1`.
#
# NOTE: Your results may vary concerning which one is fastest. Try them out.
# NOTE: The calculated output of the different FFT libraries are equal to each
# other within high significance at the moment of writing.
FFT_lib = rocketfft

# ------------------------------------------------------------------------------
# Number of concurrent workers. Each worker will spawn a separate thread
# (concurrent multithreading) that will process a chunk of all available IWs
# over which the 2D FFT correlations are to be calculated. The chunks will get
# evenly divided over the specified number of workers.
# NOTE: This number is not limited by the number of logical CPU processors: The
# workers are running in concurrent threads, not concurrent processes.
# NOTE: 32 seems to be sufficient to reach maximum speed.
N_workers = 32

# ------------------------------------------------------------------------------
# Number of threads to use for each single FFT operation.
# NOTE: Leave it to 1 thread per FFT operation, because the IWs it will operate
# on are generally too small of a size to benefit from multiple threads.
N_FFT_threads = 1



[Debugging]

# ------------------------------------------------------------------------------
# Print debug info to the terminal? Slow!
debug = False

# ------------------------------------------------------------------------------
# When True, also requires `load_mpl = True`. Slow!
show_correlation_maps = False

# ------------------------------------------------------------------------------
# Load matplotlib into memory and show vector map results?
load_mpl = True