[Source]

# ------------------------------------------------------------------------------
# Image source
#   disk  : Read image files from disk. Needs `image_path` set.
#   webcam: Live capture from webcam. Needs `camera_id` set.
#   Ximea : Live capture from Ximea camera. Needs `camera_id` set.
image_source = disk

# ------------------------------------------------------------------------------
# Absolute or relative path to the image files in case of `image_source = disk`.
# The path should end in a wildcard pointing to the images to read, e.g.
#   ../demo_images/PIV_rising_vortex_plume/*.png
image_path = ../demo_images/BOS_heated_water/*.png

# ------------------------------------------------------------------------------
# Id of the camera to connect to in case of `image_source = webcam | Ximea`. If
# only one camera is attached the id will be 0.
camera_id = 0

# ------------------------------------------------------------------------------
# Wanted resolution in case of `image_source = webcam | Ximea`. Not garantueed
# you will obtain it.
# Common options:
#   [1280, 720]   # 16:9  0.9 MPx
#   [1024, 1024]  # 1:1   1.0 MPx
#   [1600, 896]   # 16:9  1.4 MPx
#   [1920, 1080]  # 16:9  2.1 MPx
wanted_resolution = [1280, 720]



[Processing]

# ------------------------------------------------------------------------------
# Mode:
#   PIV
#       Particle image velocimetry using equidistantly timed frames.
#       (frame_0, frame_1), (frame_1, frame_2), (frame_2, frame_3), ...
#
#   PIV2
#       Particle image velocimetry using image pairs.
#       (frame_0, frame_1), (frame_2, frame_3), (frame_4, frame_5), ...
#
#   BOS
#       Background-oriented Schlieren.
#       (frame_0, frame_1), (frame_0, frame_2), (frame_0, frame_3), ...
mode = BOS

# ------------------------------------------------------------------------------
# List of square interrogation window sizes in [px] for the multigrid analysis.
# Use powers of two with each subsequent IW size the exact half of the previous
# IW size. Generally, you should not go smaller than 32 or 16 px.
# HINT: PIV usually benefits from using a multigrid analysis. BOS tends to not
# need it and work just fine using a single small IW size.
IW_sizes = [16]

# ------------------------------------------------------------------------------
# Interrogation window overlap fraction [0 - 0.8]. Only the last multigrid stage
# will have window overlapping applied to it.
IW_overlap = 0.5



[Plotting]

colormap_name = jet
colormap_clip_color = (1.0, 0, 0.58)
pixel_displacement_at_max_colormap_value = 0.85
quiver_size = 14



[Advanced]

# ------------------------------------------------------------------------------
# FFT library to use for computing 2D correlations:
#   rocketfft
#       The fastest of all, because `rocketfft` is fully jitted by numba and
#       releases the GIL.
#
#   scipy
#       Slightly slower than `rocketfft`. Also `scipy` is fully jitted by numba
#       and releases the GIL.
#
#   pyfftw
#       The slowest of all, because `pyfftw` can not be jitted by numba and
#       does not release the GIL when `N_FFT_threads = 1`.
#
# NOTE: Your results may vary concerning which one is fastest. Try them out.
# NOTE: The calculated output of the different FFT libraries are equal to each
# other within high significance at the moment of writing.
FFT_lib = rocketfft

# ------------------------------------------------------------------------------
# Maximum number of concurrent workers. Each worker will spawn a separate thread
# (concurrent multithreading) that will process a chunk of the available IWs
# over which the 2D FFT correlations are to be calculated. The chunks will get
# evenly divided over the workers, up to a maximum as given below.
# NOTE: This number is not limited by the number of logical CPU processors: The
# workers are running in concurrent threads, not concurrent processes.
# NOTE: 64 seems to be sufficient to reach maximum speed in most situations.
max_workers = 64

# ------------------------------------------------------------------------------
# Number of threads to use for each single FFT operation.
# NOTE: Leave it to 1 thread per FFT operation, because the IWs it will operate
# on are generally too small of a size to benefit from multiple threads.
N_FFT_threads = 1
