function show_IW_borders(h_ax, IW_grid, iIW, thisColor)
  % Plot a box with color 'thisColor' in axes 'h_ax' as indication of the
  % interrogation window with index 'iIW' inside of the 'IW_grid' structure
  %
  % Dennis van Gils
  % 24-02-2016

  plot(h_ax, [IW_grid.x_range(iIW, 1) IW_grid.x_range(iIW, 1) ...
              IW_grid.x_range(iIW, 2) IW_grid.x_range(iIW, 2) ...
              IW_grid.x_range(iIW, 1)] + ...
             [-.5 -.5 .5 .5 -.5], ... % esthetiques
             [IW_grid.y_range(iIW, 1) IW_grid.y_range(iIW, 2) ...
              IW_grid.y_range(iIW, 2) IW_grid.y_range(iIW, 1) ...
              IW_grid.y_range(iIW, 1)] + ...
             [-.5 .5 .5 -.5 -.5], ... % esthetiques
             '-', 'Color', thisColor, 'LineWidth', 2)
end